#!/bin/bash
rsync -aP /etc/vim/ ./vim
rsync -aP ~/.i3/ ./.i3
rsync -aP ~/.bash_custom.d/ ./.bash_custom.d
rsync -aP ~/.bashrc .
rsync -aP ~/.vim/ ./.vim
rm ./.bash_custom.d/.git -rf
rm ./.i3/.git -rf
rm ./vim/.git -rf

